spring.application.name=college-event-website
server.port=8086
# Actuator Endpoints
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Graphite Configuration
management.metrics.export.graphite.enabled=true
management.metrics.export.graphite.host=host.docker.internal
management.metrics.export.graphite.port=2003
management.metrics.export.graphite.step=10s

# Application Name
management.metrics.export.graphite.host=localhost